package callcenter;

import EstructuraBD.conexion;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mariana Valencia
 */
public class Contenido13 extends javax.swing.JInternalFrame {
    
    private EstructuraBD.conexion con = new conexion();
    private String id = "", mensaje = "";
    public UIManager UI = new UIManager();

    /**
     * Creates new form Contenido11
     */
    public Contenido13() {
        initComponents();
        UI.put("OptionPane.background", new ColorUIResource(0, 51, 51));
        UI.put("Panel.background", new ColorUIResource(0, 51, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bajas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(630, 430));
        setMinimumSize(new java.awt.Dimension(630, 430));
        setPreferredSize(new java.awt.Dimension(630, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(0, 51, 51));
        jTextField2.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 190, 30));

        jPasswordField3.setEditable(false);
        jPasswordField3.setBackground(new java.awt.Color(0, 51, 51));
        jPasswordField3.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField3.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 190, 30));

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clave administrador:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 30));

        bajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/baja1.png"))); // NOI18N
        bajas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bajas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bajasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bajasMouseExited(evt);
            }
        });
        getContentPane().add(bajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo1v2.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(630, 410));
        jLabel2.setMinimumSize(new java.awt.Dimension(630, 410));
        jLabel2.setPreferredSize(new java.awt.Dimension(630, 410));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajasMouseEntered
        // TODO add your handling code here:
        bajas.setIcon(new ImageIcon(getClass().getResource("/recursos/baja2.png")));
    }//GEN-LAST:event_bajasMouseEntered

    private void bajasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajasMouseExited
        // TODO add your handling code here:
        bajas.setIcon(new ImageIcon(getClass().getResource("/recursos/baja1.png")));
    }//GEN-LAST:event_bajasMouseExited

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        mensaje = "<html><font color=#FFFFFF>Nombre invalido...";
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user = "";
            try {
                user = jTextField2.getText().toUpperCase();
                if ("".equals(user)) {
                    JOptionPane.showMessageDialog(this, mensaje);
                } else {
                    con.busqueda_supervisores("supervisores", "nombre_supervisor", user);
                    id = con.registro_busqueda2;
                    jPasswordField3.setEditable(true);
                    jPasswordField3.requestFocus();
                    if ("".equals(con.registro_busqueda)) {
                        mensaje = "<html><font color=#FFFFFF>Usuario invalido...";
                        JOptionPane.showMessageDialog(null, mensaje);
                        jTextField2.setText("");
                        jTextField2.requestFocus();
                    } else {
                        jPasswordField3.setEditable(true);
                        jPasswordField3.requestFocus();
                    }
                }
//            JOptionPane.showMessageDialog(null, con.registro_busqueda);
            } catch (HeadlessException e) {
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void bajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajasMouseClicked
        // TODO add your handling code here:
        try {
            String pass = "";
            mensaje = "<html><font color=#FFFFFF>Eliminacion completada";
            pass = jPasswordField3.getText();
            con.busqueda_gral("administrador", "password_admin");
            if (pass.equals(con.registro_busqueda)) {
                con.eliminar("supervisores", "id_supervisor='" + id + "';");
                JOptionPane.showMessageDialog(null, mensaje, "Mensaje Informacion", JOptionPane.INFORMATION_MESSAGE);
                jTextField2.setText("");
                jPasswordField3.setText("");
                jPasswordField3.setEditable(false);
            } else {
                mensaje = "<html><font color=#FFFFFF>Contraseña invalida";
                JOptionPane.showMessageDialog(null, mensaje, "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                jPasswordField3.setText("");
                jPasswordField3.requestFocus();
            }
        } catch (HeadlessException e) {
        }

    }//GEN-LAST:event_bajasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bajas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
