package callcenter;

import EstructuraBD.conexion;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mariana Valencia
 */
public class Contenido12 extends javax.swing.JInternalFrame {
    
    private String usuario = "";
    private EstructuraBD.conexion con = new conexion();
    private String pass1 = "", pass2 = "";

    /**
     * Creates new form Contenido11
     */
    public Contenido12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        altas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(630, 430));
        setMinimumSize(new java.awt.Dimension(630, 430));
        setPreferredSize(new java.awt.Dimension(630, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 190, 30));

        jPasswordField3.setBackground(new java.awt.Color(0, 51, 51));
        jPasswordField3.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, 30));

        jPasswordField1.setBackground(new java.awt.Color(0, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 190, 30));

        altas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/alta1.png"))); // NOI18N
        altas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        altas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                altasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                altasMouseExited(evt);
            }
        });
        getContentPane().add(altas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 300, 30));

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, 30));

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del empleado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 30));

        jTextField2.setBackground(new java.awt.Color(0, 51, 51));
        jTextField2.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo1v2.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(630, 410));
        jLabel2.setMinimumSize(new java.awt.Dimension(630, 410));
        jLabel2.setPreferredSize(new java.awt.Dimension(630, 410));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void user_supervisor() {
        int cont = 0, c = 0;
        String user = "";
        int[] pos = new int[3];
        usuario = jTextField1.getText().toUpperCase();
        cont = usuario.length();
        for (int i = 0; i < cont; i++) {
            if (usuario.charAt(i) == ' ') {
                pos[c] = i;
                c++;
            }
        }
        if (c == 3) {
            user = usuario.substring(0, pos[0]) + usuario.substring(pos[1] + 1, pos[2]);
            
        } else if (c == 2) {
            user = usuario.substring(0, pos[0]) + usuario.substring(pos[0] + 1, pos[1]);
        } else {
            user = usuario.substring(0, pos[0]) + usuario.substring(pos[0] + 1, cont);
        }
//                JOptionPane.showMessageDialog(null, user);
        jTextField2.setText(user);
        jTextField2.setEditable(false);
        jPasswordField3.requestFocus();
        
    }
    

    private void altasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altasMouseClicked
        // TODO add your handling code here:
        try {
            con.agregar("supervisores", "nombre_supervisor,password_supervisor", jTextField2.getText() + "," + pass2);
            JOptionPane.showMessageDialog(null, "Insercion completada", "Mensaje Informacion", JOptionPane.INFORMATION_MESSAGE);
            jTextField1.setText("");
            jTextField2.setText("");
            jPasswordField1.setText("");
            jPasswordField3.setText("");
        } catch (HeadlessException e) {
        }
        

    }//GEN-LAST:event_altasMouseClicked

    private void altasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altasMouseEntered
        // TODO add your handling code here:
        altas.setIcon(new ImageIcon(getClass().getResource("/recursos/alta2.png")));
    }//GEN-LAST:event_altasMouseEntered

    private void altasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altasMouseExited
        // TODO add your handling code here:
        altas.setIcon(new ImageIcon(getClass().getResource("/recursos/alta1.png")));
    }//GEN-LAST:event_altasMouseExited

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                user_supervisor();
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                pass1 = jPasswordField3.getText();
                jPasswordField1.requestFocus();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jPasswordField3KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                pass2 = jPasswordField1.getText();
                if (pass2.equals(pass1)) {
                    altas.requestFocus();
                } else {
                    jPasswordField1.setText("");
                    jPasswordField1.requestFocus();
                    JOptionPane.showMessageDialog(null, "Difiere campo contraseña", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (HeadlessException e) {
            }
        }

    }//GEN-LAST:event_jPasswordField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
